ui: mocha-bdd
browsers:
  - name: chrome
    version: 35..latest
  - name: ie
    version: 9..latest
  - name: firefox
    version: 30..latest
  - name: safari
    version: 6..latest
  - name: android
    version: 4.2..latest
  - name: iphone
    version: 7.0..latest